CONTAINER_PREFIX: dsp_
CONTAINER_NAME: default
CONTAINER_WORKDIR_PATH: /app
CONTAINER_PORT: 5000

EXTERNAL_WORKDIR_PATH: ./app
EXTERNAL_PORT: 5000

REQUIREMENTS_FILE: requirements.txt

# Server settings
DEVELOPMENT: true

# Service versions
PYTHON_VERSION: 3.9
