CONTAINER_PREFIX: dsp_
CONTAINER_NAME: default
CONTAINER_WORKDIR_PATH: /var/www
CONTAINER_PORT: 5000

EXTERNAL_WORKDIR_PATH: ./www
EXTERNAL_PORT: 80

REQUIREMENTS_FILE: requirements.txt

# Server settings
DEVELOPMENT: true

# Service versions
PYTHON_VERSION: 3.9
